services:
  - type: web
    name: deepseascans
    runtime: php
    buildCommand: composer install --no-dev --optimize-autoloader && php artisan config:cache && php artisan route:cache && php artisan view:cache && php artisan migrate --force && php artisan db:seed --force
    startCommand: php -S 0.0.0.0:10000 -t public public/index.php
    plan: free 