services:
  - type: web
    name: deepseascans
    runtime: php
    buildCommand: npm install && npm run build && composer install --no-dev --optimize-autoloader && mkdir -p storage/framework/sessions storage/framework/views storage/framework/cache && chmod -R 755 storage bootstrap/cache && php artisan storage:link && php artisan migrate --force && php artisan db:seed --force
    startCommand: php -S 0.0.0.0:10000 server.php
    plan: free 